name: open-geo-tutorial
dependencies:
    - python=3.4
    - gdal>=1.9.0
    - matplotlib>=1.3.1
    - numpy>=1.8.1
    - pandas>=0.14.1
    - scipy>=0.14.0
    - scikit-learn>=0.15.0
    - notebook>=4.0
